### PR TITLE
make ip_counter use client_ip per default. 

### PR DESCRIPTION
**Pull request by vixns**
Allow to be the first of multiple captured headers.

### CODE REVIEW

**Comment by gforcada** [comment]
@vixns thanks for the pull request I'm rather busy these days but ping me again if within a week I haven't given any feedback on the pull request. Sorry for the delay.

**Comment by PatrikNorrgard** [comment]
Please accept this PR, as this is exactly what I need.

**Comment by gforcada** [comment]
@PatrikNorrgard thanks for bringing this up, I will try to review/merge and push it in the next few days, I'm (again :sweat_smile: ) rather busy right now. Please remind me within a few days/next week if I did not get around to reply.

**Comment by PatrikNorrgard** [comment]
@gforcada Thanks for replying :) I can also confirm that this works as expected, I did manually download the committed files on top of the normal install.

**Comment by gforcada** [comment]
@vixns @PatrikNorrgard I made a new release: 3.0.0 with this fix, let me know if it works, and specially if it does not :wink:

**Pull request merged**
