### PR TITLE
Improve performance of cmd_print

### PR DESCRIPTION
**Pull request by pts-kevinqiu**
My log file has about 25k log entries after filtering. With the previous
implementation, `cmd_print` hangs for a long time with CPU at 100%.

Using for loop and concate a string is expensive, since the previous
`data` object is thrown away and may get GC'ed.

Switched to a list comprehension and this function finished in 0.01
second (on pypy, haven't tested it on cpython).

### CODE REVIEW

**Comment by gforcada** [comment]
@pts-kevinqiu Wow cool! Thanks for looking into this. The only performance related action I did on the code is creating the pickle files, I never checked the commands/filters performance.

Two things before I merge this pull request:
- would you mind squashing together the last 3 commits? So that the pull request only has two commits
- please add a change log entry on ``CHANGES.rst``

Thanks!!

**Comment by kevinjqiu** [comment]
@gforcada Done :)

**Comment by pts-kevinqiu** [comment]
@gforcada Done :)

**Comment by gforcada** [comment]
@pts-kevinqiu and ``haproxy_log_analysis`` 2.0.2 is out! Thanks a lot!

**Pull request merged**
