### PR TITLE
Adding support for journalctl dump and v6 addressing

### PR DESCRIPTION
**Pull request by valleedelisle**
Journalctl under RHEL uses a timestamp that wasn't detected
by the regex. Also, adding support for v6 addressing

### CODE REVIEW

**Comment by gforcada** [comment]
@valleedelisle thanks for, another!, pull request :+1: 

Would you mind adding a test to ensure the format is parsed properly and future refactorings do not miss the changes you added?

After that I can make a release with the other (already merged) pull request and this one :100:

**Comment by valleedelisle** [comment]
@gforcada Thanks for the merge, I appreciate it! I've added a test, but I don't have much experience with unit tests so let me know if it's enough or if there's something else I need to validate.

**Comment by gforcada** [comment]
Thanks for the tests!

**Comment by valleedelisle** [comment]
Thanks for the merge!

**Pull request merged**
